export const PAGE_QUERY = 'page=';
export const UNAVAILABLE_QUERY = 'includeUnavailables='
export const PRICE_QUERY = 'price='
export const HOUR_QUERY = 'hour='
export const DAY_QUERY = 'day='
export const LICENSE_QUERY = 'license='
export const CLINIC_QUERY = 'clinic='
export const YEAR_QUERY = 'year='
export const MONTH_QUERY = 'month='
export const TIME_QUERY = 'time='

export const PATIENT_PATH = '/patients';
export const FAVORITE_PATH = '/favorites'
export const LOGIN_PATH = '/login';
export const PREPAIDS_PATH = '/prepaids';
export const LOCATIONS_PATH = '/locations';
export const SPECIALTIES_PATH = '/specialties';
export const DOCTORS_PATH = '/doctors';
export const CLINICS_PATH = '/clinics';
export const ALL_PATH = '/all';
export const EMAIL_PATH = '/email';
export const IMAGE_PATH = '/image';
export const APPOINTMENT_PATH = '/appointments';
export const AVAILABLE_PATH = '/available'
